### ISSUE TITLE
Each column takes up 1/3rd of the sheet

### ISSUE THREAD

**Issue by SLinxTheFox** [JPMeehan/roll-table-view#3]
Instead of looking like the nice and neat pictures displayed, the left two columns are much bigger and it squashes the text
![Screenshot 2024-05-17 134127](https://github.com/JPMeehan/roll-table-view/assets/44953602/59fd0e54-7a24-4910-8f55-3fa79543b58c)

I tested this without any other modules installed in V11.315, dnd5e 3.1.2, and module version 1.0.2

**Comment by JPMeehan** [comment]
Browser? Other modules?

**Comment by SLinxTheFox** [comment]
This was done in the app and I tested it without any other modules enabled

**Comment by JPMeehan** [comment]
I've been fully unable to replicate this. I suspect this is related to the internal electron version of your app being out of date and breaking the CSS.

**Comment by SLinxTheFox** [comment]
I just uninstalled and reinstalled to get any new electron client version, but the version is the same as it was before and the roll table looks the same, are you on another version of foundry than me or possibly another system version?

if not/if you already tried that, then I see the "won't fix" tag so thanks for looking at the issue and responding anyways

**Comment by JPMeehan** [comment]
OK, dug in a little - the issue is this module uses nested CSS, which isn't supported by Electron 108. Using a browser OR updating to v12 will fix this. https://caniuse.com/css-nesting

**Comment by JPMeehan** [comment]
After some tips from another developer I believe this issue should be fixed for both the v11 and v12 electron clients with the latest 1.0.3 release

**Comment by SLinxTheFox** [comment]
It does! thank you very much!
